theme: jekyll-theme-cayman
title: Atanu Ray
description: ML portfolio


# Your name to show in the footer
author: Atanu Ray


avatar: "images/profile.jpg"
round-avatar: true
title-img: "images/profile.jpg"


navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
  
social-network-links:
  email: "someone@example.com"
  github: Guillaume Prevost
  linkedin: Guillaume Prevost
